name: release

on:
  create:
    tags:

jobs:
  before-release:
    uses: ansible-community/ansible-compat/.github/workflows/tox.yml@main

  release:
    environment: release
    name: release ${{ github.event.ref }}
    needs: before-release
    uses: ansible-community/devtools/.github/workflows/release.yml@main
    with:
      pypi: true
