---
name: tox

on:
  push:
    branches:
      - "main"
      - "releases/**"
      - "stable/**"
  pull_request:
    branches:
      - "main"
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tox:
    uses: ansible/team-devtools/.github/workflows/tox.yml@main
    with:
      jobs_producing_coverage: 11
      other_names: |
        docs
        lint
        pkg
        py39-ansible214
        py39-ansible215
        py310-ansible215
        py310-ansible217
        py311-ansible215
        py312-ansible216
        py312-ansible217
        py312-devel
        py313-devel
        py310-macos:tox -e py310
        py313-macos:tox -e py313
        smoke
      skip_explode: "1"
